#!/usr/bin/env bash
# Acceptance stage - auto-generate acceptance-questions.md by dogfooding the
# fresh wiki. Runs AFTER validate passes and BEFORE apply_commit, so the
# questions generated reflect the just-applied wiki.
#
# Regeneration policy: only overwrites acceptance-questions.md when the
# current file is the scaffold default (version sentinel matches). Operator
# edits are sticky - once a project has real human-curated questions, this
# stage is a no-op.

set -euo pipefail

AGENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$AGENT_DIR/../../.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  agents/update/05-acceptance/run.sh --project <key> [--project-dir <path>] --run-dir <path>
EOF
}

die() { echo "error: $*" >&2; exit 1; }

project_key=""
project_dir=""
run_dir=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) project_key="${2:?}"; shift 2 ;;
    --project-dir) project_dir="${2:?}"; shift 2 ;;
    --run-dir) run_dir="${2:?}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown arg: $1" ;;
  esac
done

[[ -n "$project_key" ]] || die "--project is required"
[[ -n "$run_dir" ]] || die "--run-dir is required"
if [[ -z "$project_dir" ]]; then
  project_dir="$ROOT_DIR/projects/$project_key"
fi
[[ -d "$project_dir" ]] || die "project dir not found: $project_dir"
[[ -f "$run_dir/ranking-snapshot.json" ]] || die "ranking-snapshot.json missing in $run_dir"

python3 - "$project_key" "$project_dir" "$run_dir" "$AGENT_DIR" "$ROOT_DIR" <<'PY'
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

project_key = sys.argv[1]
project_dir = Path(sys.argv[2])
run_dir = Path(sys.argv[3])
agent_dir = Path(sys.argv[4])
root_dir = Path(sys.argv[5])

sys.path.insert(0, str(root_dir))
from agents.update._shared import llm_client

config = json.loads((agent_dir / "config.json").read_text())
target_count = config["stage_specific"]["target_question_count"]
min_count = config["stage_specific"]["min_question_count"]
scaffold_sentinel = config["stage_specific"]["scaffold_version_sentinel"]

project_json = json.loads((project_dir / "state" / "project.json").read_text())
aq_rel = project_json.get("acceptance_questions_path", "acceptance-questions.md")
aq_path = project_dir / aq_rel

# Decide whether to (re)generate. Skip if operator has already curated.
if aq_path.is_file():
    existing = aq_path.read_text()
    version_match = re.search(r"<!-- version:\s*([^\s>]+)\s*-->", existing)
    current_version = version_match.group(1) if version_match else "unknown"
    # Count non-discipline questions (lines that start with "N. [")
    question_lines = [
        line for line in existing.splitlines()
        if re.match(r"^\d+\.\s+\[", line.strip())
    ]
    is_scaffold = (
        current_version == scaffold_sentinel
        and len(question_lines) <= 1
    )
    if not is_scaffold:
        print(
            f"acceptance: skipping regen (version={current_version}, "
            f"questions={len(question_lines)}); operator edits are sticky"
        )
        sys.exit(0)

ranking = json.loads((run_dir / "ranking-snapshot.json").read_text())
index_md_path = project_dir / "index.md"
index_content = index_md_path.read_text() if index_md_path.is_file() else ""

wiki_pages = []
wiki_root = project_dir / "wiki"
if wiki_root.is_dir():
    for page in sorted(wiki_root.rglob("*.md")):
        wiki_pages.append({
            "path": str(page.relative_to(project_dir)),
            "content": page.read_text(),
        })

if not wiki_pages:
    print("acceptance: no wiki pages found; skipping (nothing to probe against)")
    sys.exit(0)

prompt = json.dumps({
    "project_key": project_key,
    "project_name": project_json.get("name", project_key),
    "ranking_snapshot": ranking,
    "wiki_pages": wiki_pages,
    "index_content": index_content,
    "target_question_count": target_count,
})

try:
    result = llm_client.invoke(stage_id="05-acceptance", prompt=prompt)
except RuntimeError as exc:
    print(f"acceptance: generation failed: {exc}", file=sys.stderr)
    sys.exit(0)  # non-fatal; operator can still hand-write questions

response = result["response"]
questions = response.get("questions", [])
if len(questions) < min_count:
    print(
        f"acceptance: generated only {len(questions)} questions "
        f"(min {min_count}); keeping existing scaffold",
        file=sys.stderr,
    )
    sys.exit(0)

version = response.get("version", "auto.1")
bar_total = response.get("acceptance_bar_total", int(2 * len(questions) * 0.75))
bar_max = response.get("acceptance_bar_max", 2 * len(questions))

lines = [
    f"# Acceptance Questions - {project_json.get('name', project_key)}",
    "",
    f"<!-- version: {version} -->",
    "",
    (
        "Questions a cold LLM session should be able to answer from the wiki "
        "alone. Auto-generated by the acceptance stage; edit freely - your "
        "edits are sticky and won't be overwritten by future update runs."
    ),
    "",
]

for idx, question in enumerate(questions, start=1):
    tag = question.get("tag", "lookup")
    text = question.get("text", "").strip()
    target = question.get("targets_domain")
    hint = question.get("expected_citation_hint")
    line = f"{idx}. [{tag}] {text}"
    if target or hint:
        annotations = []
        if target:
            annotations.append(f"targets: {target}")
        if hint:
            annotations.append(f"expected: {hint}")
        line += f"  <!-- {' | '.join(annotations)} -->"
    lines.append(line)

lines.extend([
    "",
    "## Scoring",
    "",
    "- 2: full answer with citations from wiki alone",
    "- 1: directional but incomplete or uncited",
    "- 0: can't answer; wrong; wiki contradicts itself",
    "",
    "## Acceptance bar",
    "",
    f"- Total >= {bar_total}/{bar_max}",
    "- No zero on [discipline]-tagged questions",
])

aq_path.write_text("\n".join(lines) + "\n")

now = datetime.now(timezone.utc).isoformat()
update_state_path = project_dir / "state" / "update-state.json"
if update_state_path.is_file():
    update_state = json.loads(update_state_path.read_text())
    update_state.setdefault("stages", {})
    update_state["stages"]["acceptance"] = {
        "status": "completed",
        "last_run_dir": str(run_dir),
        "last_completed_at": now,
        "summary_file": str(aq_path),
        "question_count": len(questions),
        "version": version,
    }
    update_state_path.write_text(json.dumps(update_state, indent=2) + "\n")

print(
    f"acceptance: generated {len(questions)} question(s), version={version}, "
    f"bar={bar_total}/{bar_max}"
)
PY
